### ISSUE TITLE
Add a venv for the dependencies.

### ISSUE THREAD

**Issue by jamnaritesh** [ValyrianTech/ComfyUI_with_Flux#3]
Thanks for the great image, I had few suggestions after using the image for a couple days.
1. The docker base images gets wiped (/usr/lib/python3.10/dist) when we restart so it might be better to have a venv inside workplace itself so that we don't lose those after restart.
2. Add start script inside workplace, that way we can make changes to the start script if needed.

**Comment by WouterGlorieux** [comment]
I misunderstood you last time because at the time I wasn't aware of the issues with some custom nodes after a restart.
I have made some changes, by pre-installing a bunch of custom nodes. I also added a script to create a venv, however that should be used only as a last resort.

I also moved the start script to the workspace so it is persistent and users can now make modifications to it.

**Comment by jamnaritesh** [comment]
np mate, Thanks @WouterGlorieux for the great work!
